# -*- coding: utf-8 -*-
"""CMC_API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17W8xiMUrnPqdrxmDCNFa23UT687iu5G2
"""

from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json

# listing of top 200 (per 1 credit) by market cap
url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
parameters = {
  'start':'1',
  'limit':'200',
  'convert':'USD'
}
headers = {
  'Accepts': 'application/json',
  'X-CMC_PRO_API_KEY': '5cbb1552-e1d6-4a75-a97b-d1af64d73856',
}

session = Session()
session.headers.update(headers)

try:
  response = session.get(url, params=parameters)
  data_listing = json.loads(response.text)
except (ConnectionError, Timeout, TooManyRedirects) as e:
  print(e)

# access CMC ID field in JSON to use for metadata
cmc_id=[]
for project in data_listing['data']:
  #print(str(project['cmc_rank'])+'. '+project['name']+', CMC ID: '+str(project['id']))
  cmc_id.append(project['id'])

# trim the string for testing
testID=cmc_id[0:5]
testID

#IDString=''
#for id in cmc_id:
#    IDString = IDString + str(id) +','
#IDString = IDString[:-1]
testIDString=''
for id in testID:
    testIDString = testIDString + str(id) +','
testIDString = testIDString[:-1]
print(testIDString)

# listing of metadata
url = 'https://pro-api.coinmarketcap.com/v2/cryptocurrency/info'
parameters = {
  'id':testIDString,
}
headers = {
  'Accepts': 'application/json',
  'X-CMC_PRO_API_KEY': '5cbb1552-e1d6-4a75-a97b-d1af64d73856',
}
session = Session()
session.headers.update(headers)

try:
  response = session.get(url, params=parameters)
  metadata = json.loads(response.text)
except (ConnectionError, Timeout, TooManyRedirects) as e:
  print(e)

# access date::<key>::urls::sourcecode field
source=[]
for project in metadata['data']:
  id = project
  sc = metadata['data'][id]['urls']['source_code']
  source.append(sc)

source

sd = {}

import pandas as pd 
 
# Creates DataFrame. {'col':L}
df = pd.DataFrame({'cmc_id':cmc_id[0:5]}) 

# Print the data 
df

df['source code']=source

df

